### PR TITLE
Start kited at startup.

### PR DESCRIPTION
**Pull request by airblade**
See #136.

Two outstanding questions:

- How to launch kited on Windows?
- How can the user change the 'start kited at startup' setting?

### CODE REVIEW

**Comment by airblade** [comment]
@jansorg I made some changes which work for me – please could you try it again?

BTW, I noticed every time I launch Kite on Windows it overwrites my own checkout of the vim plugin, which makes local changes slower to test ;)

**Comment by jansorg** [comment]
@airblade Thanks, the path to kited.exe seems to be correct now. 
The weird thing is that kited is not started when I launch gvim but when I quit it:
1. make sure to stop kited.exe using the task manager
2. start gvim
3. at this point kited is not started
4. stop gvim
5. now kited appears in the process list of the task manager

Is it possible that the start is not taking effect until gvim is quit?

**Comment by airblade** [comment]
@jansorg How can our Windows VMs be so different?!  I'll take a look at this.  I can't imagine why kited would launch only when gvim exits...

**Comment by jansorg** [comment]
@airblade I really don't know! Which version of vim are you using on Windows? I'm using GVim 8.1.x ...

**Comment by airblade** [comment]
@jansorg I'm using gVim 8.1.x on Win10.  This is what I get:

* make sure to stop kited.exe using the task manager
* start gvim
* at this point kited starts and appears in the list of the task manager

**Comment by airblade** [comment]
Have you got the latest commit (240e0a8)?

**Comment by jansorg** [comment]
@airblade Thanks! I've tested with the latest commit and I'm still seeing this behaviour. Could this be caused by a settings or something else in my or your vim configuration?
Which version of gVim exactly are you using? I've tested with gVim 8.1.0001 (vim.org) and 8.1.0895 (https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0895).

**Comment by jansorg** [comment]
@airblade I'm seeing this message window, too.
It turned out that kited.exe was started properly but it it didn't show up in the process manager as long as vim was running. Perhaps that's a difference between Win 8 and Windows 10.
This PR now seems to be what we want. I'd like to wait for one of the next Kite updates, though. I want to make sure that the icon is properly showing in the system tray on Windows even when the process isn't shown in the process list. I expect that the next kite update will   re-enabled the icon.

**Comment by airblade** [comment]
Rebased onto master.

**Pull request closed without merging**
