### PR TITLE
Pass data via stdin

### PR DESCRIPTION
**Pull request by airblade**
The plugin code is complete but the `kite-http` helper binaries are yet to be updated (PR pending for them in their repo).

See #180.

### CODE REVIEW

**Comment by jansorg** [comment]
@airblade I'll test and review when the new binaries were updated in this PR.

**Comment by airblade** [comment]
@jansorg I have updated the kite-http binaries.

**Comment by LarsMichelsen** [comment]
Nice, thanks! Works for me :+1: 

Just for interest, where can I find the sources for the kite-http binaries?

**Comment by airblade** [comment]
@LarsMichelsen Thanks for confirming.

The kite-http source is in a private repo; @jansorg will know whether it could be opened up.

**Comment by jansorg** [comment]
@airblade 
This happened on NeoVim on Windows: 
Screenshot_20190605_170646

NeoVim on Linux: 
Screenshot_20190605_172720

**Comment by airblade** [comment]
@jansorg Oops, I accidentally committed a change which inverted the vim/neovim logic while I was testing it.  I've pushed a new commit removing it.  Sorry!

**Comment by jansorg** [comment]
@LarsMichelsen The sources of the helper binary are now available at https://github.com/kiteco/vim-plugin-helper

**Comment by LarsMichelsen** [comment]
@jansorg Thank you.

**Comment by LarsMichelsen** [comment]
I experience some "stdin closed" issues after using nvim in a shell. 

I am not sure whether or not this is related, but this change was the first thing I thought of.

It looks like this:

1. Open a shell
2. Try to read something from stdin, works:

```
> read x
```

3. Open and exit nvim again
4. Try to read something from stdin again:

```
> read x
bash: read: read error: 0: Resource temporarily unavailable
```

**Comment by airblade** [comment]
@LarsMichelsen I can't reproduce the `Resource temporarily unavailable` error.

The code explicitly closes the job's stdin to avoid this kind of problem:

https://github.com/kiteco/vim-plugin/blob/b8e0ac76b2ac5a445d98d4b9ee278e88c8495511/autoload/kite/async.vim#L54

Do you get this when the Kite vim plugin is your only plugin?

**Comment by jansorg** [comment]
@airblade Thanks, the current branch is working well here.
@airblade I also wasn't able to reproduce this here (Linux). This sounds a bit like that the stdin file descriptor isn't passed as a copy to nvim. Which OS and type of shell  are you using?

**Comment by airblade** [comment]
@jansorg macOS 10.14.5, GNU bash version 3.2.57(1)-release (x86_64-apple-darwin18).

**Comment by airblade** [comment]
@LarsMichelsen Have you had the `Resource temporarily unavailable` problem again?  And with the Kite vim plugin only?

**Comment by LarsMichelsen** [comment]
@airblade Still experience this issue with nvim, but does not seem to be related to kite plugin. I removed it and the problem persists. Will dig a bit deeper now.

**Comment by LarsMichelsen** [comment]
Seems you can forget about the stdin issue. It's looks like a bare nvim problem (https://github.com/neovim/neovim/issues/10284).

**Comment by LarsMichelsen** [comment]
Good news. The problem was related to neovim itsel and is solved in current neovim master.

I think you can continue with this change.

**Comment by airblade** [comment]
Fast-forward merged: 7c91e6a...b3d3037.

**Pull request closed without merging**
