### PR TITLE
Use floating window for completeopt warning

### PR DESCRIPTION
**Pull request by airblade**
See #236.

To test this manually:

```
$ vim -c 'set cot="menu"' somefile.py
```

Then invoke an insert-mode completion with `<C-X><C-U>`, i.e. ctrl-x ctrl-u.

### CODE REVIEW

**Comment by metalogical** [comment]
In Neovim, I see a whole bunch of errors on this branch:

Screen Shot 2019-12-13 at 2 08 46 PM

**Comment by airblade** [comment]
Hmm, I can't reproduce this.  What version of nvim are you using?  And what is `:echo &cot`?

The errors messages suggest that a completion request was sent, which it shouldn't have been (assuming you were testing an unsuitable `completeopt` value).

But even with completion occurring, I can't think why you would get those errors.

**Comment by airblade** [comment]
@metalogical Does this still give you errors?

**Comment by jansorg** [comment]
@airblade Travis is failing with this. Would be great to fix this before this PR is merged, if it's just a small fix.

```
normalise version        - not ok
                           ! Test_normalise_version line 7: Expected '8.1.1-503,505-680,682-1283' but got '8.2.1-503,505-680,682-1283'
                           ! function RunTest[6]
                           ! ----
                           ! Test_normalise_version line 16: Expected '8.1.1-822' but got '8.2.1-822'
                           ! function RunTest[6]
                           ! ----
                           ! Test_normalise_version line 25: Expected '8.1.1' but got '8.2.1'
                           ! function RunTest[6]
                           ! ----
                           ! Test_normalise_version line 34: Expected '8.1.1-895' but got '8.2.1-895'
                           ! function RunTest[6]

```

**Comment by metalogical** [comment]
I still see this. It doesn't always happen immediately, and sometimes I have to do `<C-X><C-U>` to get it breaking, but it seems that once it breaks once it breaks consistently whenever I perform any action (with various stack traces).

`:echo &cot` doesn't show anything, which is unexpected I guess.
```
~ ➜ nvim --version
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190704-39939-10isiet/neovim-0.3.8/build/config -I/tmp/neovim-20190704-39939-10isiet/neovim-0.3.8/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190704-39939-10isiet/neovim-0.3.8/build/src/nvim/auto -I/tmp/neovim-20190704-39939-10isiet/neovim-0.3.8/build/include
Compiled by brew@Sierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.8/share/nvim"

Run :checkhealth for more info
```

Screen Shot 2020-01-08 at 3 59 42 PM
Screen Shot 2020-01-08 at 4 01 05 PM

**Comment by airblade** [comment]
> :echo &cot doesn't show anything, which is unexpected I guess.

@metalogical That's odd.  Are you testing like this?

```
nvim -c 'set cot="menu"' somefile.py
```

The errors you're seeing are something going wrong when completion is attempted; but this PR is about showing a better warning when completion cannot be attempted due to `completopt` being inadequate.

**Comment by airblade** [comment]
@jansorg I have fixed that unrelated failing test.

**Comment by metalogical** [comment]
yes I test with `nvim -c 'set cot="menu"' Desktop/kitetest/python/test.py`

It's possible that the errors I'm seeing would go away after merging with master? 

Separately though, I don't see any warning about `completeopt` show up.

**Comment by airblade** [comment]
> I don't see any warning about `completeopt` show up.

@metalogical That's because your nvim is v0.3.8 but and the improved warning in this PR only shows up in v0.4.0+ (because that's when floating windows were added to neovim).  So you're getting the pre-PR experience, i.e. the warnings in the command line are overwritten immediately by the mode indicator.

**Comment by metalogical** [comment]
In that case, let's get this merged, since Joachim has tested it, and the errors I'm seeing are probably either a non-issue or should be tracked separately.

**Comment by airblade** [comment]
Rebased and merged into master: d01c354...f3e5ae9.

**Pull request closed without merging**
