### PR TITLE
Add editor_version and plugin_version to event properties.

### PR DESCRIPTION
**Pull request by airblade**
See #147.

### CODE REVIEW

**Comment by airblade** [comment]
@jansorg I think the few tests which are failing in the build are failing because the JSON tests do not expect requests containing `editor_version` and `plugin_version` values.

**Comment by jansorg** [comment]
@airblade I think that it's best to require that all json properties defined in the test specification must be present and to not fail if additional properties are present in the request. So the properties in the test specification should be treated as a subset of the request properties. Does that sound reasonable?

**Comment by airblade** [comment]
@jansorg The tests pass now.

**Comment by jansorg** [comment]
@airblade Thank you!
I've tested on Windows so far. I'm seeing this value of `editor_version` in the log file: `8.1.link  /nologo /subsystem:windows,5.01 /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:i386  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   \"C:\\Tcl\\lib\\tclstub86.lib\" WSock32.lib xpm\\x86\\lib-vc14\\libXpm.lib /PDB:gvim.pdb -debug`):

```
> POST /clientapi/editor/event HTTP/1.0
> Host: localhost
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 737
> 
> {"selections":[{"end":39,"start":39}],"source":"vim","action":"edit","editor_version":"8.1.link  /nologo /subsystem:windows,5.01 /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:i386  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   \"C:\\Tcl\\lib\\tclstub86.lib\" WSock32.lib xpm\\x86\\lib-vc14\\libXpm.lib /PDB:gvim.pdb -debug","plugin_version":"1.0.18","text":"import json\r\nimport json\r\n\r\njson.dumps()","filename":"C:\\Users\\jansorg\\Python\\test.py"}
| Received complete response: 22.9023ms
< HTTP/1.0 200 OK
< Date: Wed, 27 Feb 2019 17:47:56 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
```

**Comment by airblade** [comment]
@jansorg Please could you upload a screenshot of the output of `:version` in your Windows gvim?

**Comment by jansorg** [comment]
@airblade Here it is (gvim on Windows 10):
screenshot_20190228_112340

**Comment by airblade** [comment]
@jansorg Thanks, that was helpful.  I've pushed another commit which should work auf Deutsch!

**Comment by airblade** [comment]
Rebased onto master and merged.

**Pull request closed without merging**
