### PR TITLE
Make signature completions asynchronous.

### PR DESCRIPTION
**Pull request by airblade**
See #148.

### CODE REVIEW

**Comment by airblade** [comment]
@jansorg The Travis build terminated because it stalled after downloading the kited test binary.

**Comment by jansorg** [comment]
@airblade The job on Travis doesn't seem to terminate. Is it possible that the async handling prevents vim from terminating after the json testrunner tests were executed?
https://travis-ci.com/kiteco/vim-plugin/builds/100467269

**Comment by airblade** [comment]
@jansorg Looking at the raw log, I don't think this is to do with async signature completions.  Instead I think Vim paused when its screen was filled with messages, waiting for the user to type something.  I have just pushed a commit which stops vim doing this.

**Comment by airblade** [comment]
Rebased onto master and merged.

**Pull request closed without merging**
