### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by airblade**
See #151.

### CODE REVIEW

**Comment by jansorg** [comment]
Thanks @airblade . I forgot to mention the arguments for `kited`. Could you add `--plugin-launch` to the executed kited command, please? (i.e. the same as on macOS)

**Comment by airblade** [comment]
@jansorg There you go.

**Comment by jansorg** [comment]
@airblade This is working fine on Linux!
Is it possible to redirect stdout to /dev/null? Or, if that's useful for debugging, to the kite-vim logfile?

**Comment by airblade** [comment]
@jansorg Is that stdout from the kited process?

**Comment by jansorg** [comment]
@airblade Yes, the stdout from the kited process. kited is printing a few lines to stdout on startup and this was showing up on the terminal where vim was shown.

**Comment by airblade** [comment]
@jansorg Hopefully it's ok now.

**Comment by jansorg** [comment]
Thanks @airblade !
I'm sorry, but the installation paths changed a bit:
`kited` is now at `/opt/kite/kited`. `/opt/kite` isn't in $PATH.
Could you update the launcher code to use this location instead, please? If the file doesn't exist, then nothing should be launched.

I'm not sure if this is relevant: 
Is it necessary to also update `kite_install_path()` and `kite_running()` in  `utils.vim` ?

**Comment by airblade** [comment]
@jansorg I've updated the installation path for linux (in `kite_install_path()`).  `kite_running()` doesn't need to change given that it uses the same command as on macOS.

**Comment by jansorg** [comment]
@airblade Thanks! This seems to be working well.

I'm sorry, but there are two more things:
- I think that https://github.com/kiteco/vim-plugin/pull/152/files#diff-c39ee2d7b30e782caab73431d6c48455R155 isn't handling the Linux case where the binary name is `kited` and not `Kite`
- could you also redirect stderr to /dev/null when starting kited? Sometimes kited is printing to stderr on Linux and this is mixing up the rendering of `vim` in a terminal

**Comment by airblade** [comment]
@jansorg There you go.

**Pull request merged**
