### PR TITLE
Ensure 'completeopt' always set sensibly in Kite buffers.

### PR DESCRIPTION
**Pull request by airblade**
See https://github.com/kiteco/kiteco/issues/8011.

### CODE REVIEW

**Comment by airblade** [comment]
@jansorg The only visible change should be that, even if you (or one of your other plugins) have  configured `completeopt`, you have to explicitly choose a completion option for it to be inserted, rather than the first option being inserted automatically.

It shouldn't affect whether or not the documentation is shown in the preview window, which depends on `completeopt` containing the value `preview`.

What does `:echo &completeopt` give?

**Comment by jansorg** [comment]
@airblade I'm getting this:
Screenshot_20190515_170055

I don't think that I have custom options set for my user.

**Comment by airblade** [comment]
@jansorg I'm confused ;)

- Do you see the documentation?
- Do you want to see the documenation?
- How is it different without this patch?

**Comment by jansorg** [comment]
@airblade 
- I see the documentation
- I don't wan't it as I haven't seen it before in vim
- running `master` isn't displaying the documentation
- with master `:echo &completeopt` gives `menuone,noinsert`

**Comment by airblade** [comment]
@jansorg Thanks for the clarifications.

On master we force `completeopt` to `menuone,noinsert` if and only if the user hasn't configured `completeopt` themselves.  If they have, we respect their configuration.

In this patch, we don't care whether the user has configured `completeopt`; we force it to contain `menuone,noinsert` (and remove `longest` which stops `noinsert` from working).  However in order not to completely overwrite their setting, if they made one, we add `menuone,noinsert` to whatever is already there.  Vim's default is `menu,preview`; the `preview` makes the documentation show in the preview window.  The result is that with the patch your `completeopt` becomes `menu,menuone,noinsert,preview`.

I think the "Vim way" is to leave the user to figure out that they need to remove `preview` themselves if they don't want it, perhaps aided with some documentation.  They would need to put `set completeopt-=preview` in their vimrc.

**Comment by airblade** [comment]
BTW, vim's docs for `completeopt`:

```
'completeopt' 'cot'	string	(default: "menu,preview")
			global
			{not available when compiled without the
			|+insert_expand| feature}
			{not in Vi}
	A comma separated list of options for Insert mode completion
	|ins-completion|.  The supported values are:

	   menu	    Use a popup menu to show the possible completions.  The
		    menu is only shown when there is more than one match and
		    sufficient colors are available.  |ins-completion-menu|

	   menuone  Use the popup menu also when there is only one match.
		    Useful when there is additional information about the
		    match, e.g., what file it comes from.

	   longest  Only insert the longest common text of the matches.  If
		    the menu is displayed you can use CTRL-L to add more
		    characters.  Whether case is ignored depends on the kind
		    of completion.  For buffer text the 'ignorecase' option is
		    used.

	   preview  Show extra information about the currently selected
		    completion in the preview window.  Only works in
		    combination with "menu" or "menuone".

	   noinsert Do not insert any text for a match until the user selects
		    a match from the menu. Only works in combination with
		    "menu" or "menuone". No effect if "longest" is present.

	   noselect Do not select a match in the menu, force the user to
		    select one from the menu. Only works in combination with
		    "menu" or "menuone".
```

**Comment by jansorg** [comment]
@airblade Thanks for the details on the way it's implemented now.
I assume that this means that user who did not configure a value for `completeopt` would now see the preview after an update? A change of behaviour without apparent reasons might confuse users.

If `completeopt` was set to `menu,preview`, would it be possible to find out if this was set by the user or by vim's defaults?

**Comment by airblade** [comment]
@jansorg Yes, a user who did not configure a value for `completeopt` would now see the preview window after an update.  Would you like me to revert that aspect?

And yes, we can distinguish a default `menu,preview` from a user-configured one.

**Comment by airblade** [comment]
As discussed, one advantage of leaving the default `preview` is that the user sees there is documentation available for each completion; they might not realise it exists otherwise.

**Comment by airblade** [comment]
Merged in 69def8c.

**Pull request closed without merging**
