### PR TITLE
Implement goto definition

### PR DESCRIPTION
**Pull request by airblade**
See #291.

### CODE REVIEW

**Comment by airblade** [comment]
I wasn't able to get a response locally which included a definition so I haven't been able to actually goto a definition yet.

**Comment by jansorg** [comment]
@airblade Tested on Linux, cli vim `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23). Included patches: 1-814`

I executed command `:KiteGotoDefintion` on the last line.
Code:
```
def print_hi(name):
        print(name)

print_hi("myname")
```

Screenshot_039

**Comment by airblade** [comment]
@jansorg Thanks for the simple example.  It works for me now.

**Comment by airblade** [comment]
`gd` and `gD` are the standard ones for goto local declaration and goto global declaration respectively.  But reading the docs again now, they are for declarations of variables.

For the definition of the keyword under the cursor, `CTRL-]` is the standard command.

**Comment by airblade** [comment]
Rebased and merged in a2d0bb1...63c7570.

**Pull request closed without merging**
