### PR TITLE
Disable common completion plugins which users may have installed

### PR DESCRIPTION
**Pull request by airblade**
- coc.nvim
- jedi-vim
- YouCompleteMe
- deoplete

See #178.

#### QA Instructions

Install this branch manually by (on macOS or Linux) first uninstall vim from Kite plugin manager, then:
```
mkdir -p ~/.vim/pack
cd ~/.vim/pack
rm -rf kite
git clone https://github.com/kiteco/vim-plugin.git kite
cd kite
git checkout origin/178-other-completion-plugins
```

Install each of the following and test that Kite for Vim still works:
1. https://github.com/neoclide/coc.nvim
2. https://github.com/davidhalter/jedi-vim
3. https://github.com/ycm-core/YouCompleteMe
4. https://github.com/Shougo/deoplete.nvim

To install these plugins, one easy way is to use https://github.com/junegunn/vim-plug (follow install instructions in the readme).

Once you're done, reset state by `rm -rf ~/.vim/pack/kite`, and remove the 4 plugins above.

### CODE REVIEW

**Comment by jansorg** [comment]
@airblade Are these other completion engines only disabled when a users opens a Python file or at startup?
So far I've successfully tested YouCompleteMe, coc seemed a bit complicated to setup.

**Comment by airblade** [comment]
@jansorg They're disabled when the user opens a Python file.

I agree, coc.nvim does seem complicated to setup!

**Comment by jansorg** [comment]
@airblade Thanks. I'm sorry, these should be the last questions I have.
- Have you tested with all three plugins? If you did that, then I won't go through the setup here and trust that it'll work :)
-Are the other plugins disabled for Python files only, i.e. will these plugins function as expected when the user switches from a Python file to another file?
- Do you think that users expect a setting to disable Kite's completions instead of Kite disabling other plugins?

**Comment by airblade** [comment]
@jansorg As discussed, something else to bear in mind is that as well as completions, some of these plugins provide other features which overlap with Kite, e.g. documentation.

**Comment by jansorg** [comment]
@airblade 
Test results for coc.nvim on Windows: 
coc seems to be properly disabled. A message which reads similar to "disabling coc..." shortly pops up after opening a Python file and then disappears. Could this be related to the Kite status update?

**Comment by jansorg** [comment]
@airblade Here's the test result for the `jedi-vim` plugin.
- Tested on Windows 10
- I had to install gvim 64bit, available at https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1568

- The message appeared properly (it wasn't hidden).
- But completions are handled differently now. The first option seems to be always inserted when typing a single character, e.g. typing `i` inserts `import `, then typing `j` turns this into `import json`.
- Backspace isn't working any more in insert mode

**Comment by airblade** [comment]
@jansorg I was able to reproduce the coc.nvim situation:

> A message which reads similar to "disabling coc..." shortly pops up after opening a Python file and then disappears.

It was caused by some kind of installation warning.  Once I had installed [coc-python](https://github.com/neoclide/coc-python) the message remained in place.

**Comment by airblade** [comment]
@jansorg Re jedi-vim:

> But completions are handled differently now.

It looks like jedi-vim changes the `completeopt` setting; when the Kite plugin checks the setting to see if it has been changed from the default, it has so it leaves it alone.

https://github.com/davidhalter/jedi-vim/blob/016fb7c78e3971ab662796d2abf5f2f4a227e1a1/plugin/jedi.vim#L36

https://github.com/davidhalter/jedi-vim/blob/016fb7c78e3971ab662796d2abf5f2f4a227e1a1/autoload/jedi.vim#L567-L587

Vim doesn't have a clean way of sandboxing plugins, and all these completion plugins trample on top of each other.  We can try to disable others but there's no clean way to do it and we'll always get strange interactions between them.

**Comment by jansorg** [comment]
@airblade Thanks for the feedback. Perhaps Kite should disable itself when it detects other, conflicting plugins. I'll let you know if this should be done.

**Comment by airblade** [comment]
@metalogical I have added a commit to turn off deoplete.  The only drawback is that it turns off deoplete for all buffers, not just Python ones, but nevertheless it should help.

**Comment by metalogical** [comment]
apparently, according to #197, Black also doesn't currently work with Kite.

**Comment by airblade** [comment]
I'm not sure what Black is...is there a repo on GitHub?

**Comment by metalogical** [comment]
https://github.com/psf/black/blob/master/plugin/black.vim

**Comment by plungg** [comment]
@kiteco/qa please test the fix above. Instructions are at the top. For questions, ask @jansorg (+FYI)

**Pull request merged**
