### PR TITLE
Support completions for bash, ruby, php

### PR DESCRIPTION
**Pull request by airblade**
Note that Vim often detect bash scripts as sh so we include that too.

### CODE REVIEW

**Review by jansorg — CHANGES_REQUESTED** [review]
@airblade Is the detection working on file type or file extension? afaik it should only look at the file extension, because that's what kited is doing. I'll add a note when I can provide the official list of extensions for the supported file types.
cc @metalogical

**Comment by airblade** [comment]
The detection works on filetype, although when the filetype is Python the plugin also checks the extension.

**Comment by jansorg** [comment]
@airblade Could you also check the extension for the other file types?
The list of supported is available at https://github.com/kiteco/kiteco/blob/master/kite-go/client/internal/kitelocal/permissions/support_status.go. Checking the extension after the file type was accepted should be enough. I don't think that it's necessary add a mapping `file type <> file extension` in the vim plugin.

**Comment by airblade** [comment]
If we are going to check the extension, we don't need the file type check – would you agree?

**Comment by jansorg** [comment]
Yes, I agree - unless vim disabled features like completions for file types unknown to vim. If that's not the case or all kited extensions have valid vim file types, then checking just the extension is fine.

**Comment by airblade** [comment]
If we are configuring the file extensions that kited recognises, do we still need to query the `/clientapi/languages` endpoint?

And if we do, I'll just mention that the endpoint reports language names (a.k.a. file types), not extensions.

**Comment by airblade** [comment]
The user can set the variable `g:kite_supported_languages` to opt in to the languages they want Kite's completions for.  This made sense when there were only two or three possible languages (go, python, and javascript).

Now Kite supports lots of languages and the assumption is that while the user may want to opt out of one or two languages, they will want most of the languages on offer.

However it is not easy for the user to opt out of a language or two.  It would require setting the variable to the list of available languages excluding the ones they don't want.  But where would they find the list of available languages?  Even if they could find the list, how would they keep it up to date in future?

I suggest that we support both opt in and opt out by prefixing opt-out languages with a minus.  For example:

```viml
let g:kite_supported_languages = ['-java', '-html']  " -> all kited's languages except java and html
let g:kite_supported_languages = ['python', 'go']  " -> only python and go
```

Does that sound good?

**Comment by metalogical** [comment]
👍 on opt-out for language support. But the new languages are similar to JS & Go, where they should not be on by default.

The reason for this is that we don't want to disable other completions providers when the user is coding in these languages, as the completions Kite provides may not be as comprehensive as other providers.

**Comment by airblade** [comment]
@metalogical So the default should remain Python only?

**Comment by metalogical** [comment]
@airblade correct

I'm currently working on documenting how I integrate Kite into Vim for other languages via LSP (Coc.nvim) for users who may want an alternative.

**Comment by jansorg** [comment]
@airblade apologies for the confusion here, which was caused by my suggestion.

**Comment by airblade** [comment]
@metalogical Do you have a preference for how the user could opt in to all of Kite's languages, without having to list them all out?

One approach would be to introduce a special value such as `ALL`.  For example:

```viml
let g:kite_supported_languages = ['ALL']
```

**Comment by airblade** [comment]
This is ready for another review.

**Comment by jansorg** [comment]
@metalogical Would you review this or should I do this?

**Review by metalogical — APPROVED** [review]

**Comment by airblade** [comment]
Rebased and merged in 144d6ce...3acb1be.

**Pull request closed without merging**
