### PR TITLE
Improve completion popup menu on Nvim-QT.

### PR DESCRIPTION
**Pull request by airblade**
I found a way to take care of this automatically.

See #184.

### CODE REVIEW

**Comment by airblade** [comment]
Ah, this is probably a better test: `:echo exists('g:GuiLoaded')`.  What does this give please?

**Comment by jansorg** [comment]
Hm, `:echo exists(':GuiPopupmenu')` displays `2` and `:echo exists('g:GuiLoaded')` displays `1`.
I've double-checked with `:set runtimepath` that the new branch is used. 

(Does the comman have to be ` execute 'GuiPopupmenu 0'` or ` execute ':GuiPopupmenu 0'`?)

**Comment by airblade** [comment]
> :echo exists(':GuiPopupmenu') displays 2 and :echo exists('g:GuiLoaded') displays 1.

As expected.

> Is it `execute 'GuiPopupmenu 0'` or `execute ':GuiPopupmenu 0'`?

The first one.  You can try it yourself: type a colon to go into Ex mode and then the command.  I.e. `:execute ...`.

**Comment by airblade** [comment]
@jansorg After opening Vim, you can run `:messages` which will show you `fixing nvim-qt popup menu` if the guard passed.

**Comment by airblade** [comment]
Squashed and merged in 44c1441.

**Pull request closed without merging**
